### ISSUE TITLE
Determine types of artifacts in subjects and materials fields

### ISSUE THREAD

**Issue by ywluogg** [in-toto/attestation#103]
Hi team, during uses of Intoto provenance, I noticed a use case that pipeline can produce artifact URI not in the recommended PackageURI form, but it would be still fairly valuable if there is a field in `subjects` and `materials` to let users determine the type of the artifact. Consider the following case:
```
{"name": "us-west4-maven.pkg.dev/test-project/test-repo/com/google/guava/guava/31.0/guava-31.0.jar", "digest": {"sha256": "abc"}}
```
in `subjects` and the following case:
```
{"uri": "us-west4-maven.pkg.dev/test-project/test-repo/com/google/guava/guava/31.0/guava-31.0-sources.jar", "digest": {"sha256": "xyz"}}
```
in `materials`. It would be hard to determine the artifact type just from the name or URI. If a new field can be used to determine that, such as
```
{"name": "us-west4-maven.pkg.dev/test-project/test-repo/com/google/guava/guava/31.0/guava-31.0.jar", "digest": {"sha256": "abc"}, "type": "maven_package"}
```
would be helpful.

**Comment by adityasaky** [comment]
Hi @ywluogg , is this for the SLSA provenance spec? I wonder if we can use ITE-4 URIs to indicate the package ecosystem, perhaps even going as far as pURL? That way we can avoid adding an extra field, but this discussion may belong on the SLSA forum.

cc @MarkLodato @SantiagoTorres 

ITE-4 for reference: https://github.com/in-toto/ITE/blob/master/ITE/4/README.adoc
