### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by marcelamelara** [in-toto/attestation#127]
There's a lot of redundant and/or outdated information in the files in the [docs/](https://github.com/in-toto/attestation/tree/main/docs) folder. Would be great to get that cleaned up and updated.

TODO: 
- [x] Address: https://github.com/in-toto/attestation/pull/135#discussion_r1114674137

**Comment by marcelamelara** [comment]
Include: https://github.com/in-toto/attestation/pull/135#discussion_r1114674137

**Comment by joshuagl** [comment]
We should ensure that the 'monotonic' principle is clearly articulated cc @SantiagoTorres

**Comment by joshuagl** [comment]
Some streamlining was merged in #153. Still to do:
- [ ] ensure that the 'monotonic' principle is clearly articulated 
- [ ] remove redundant examples
- [ ] fix motivating use cases to use specified attestation format

**Comment by TomHennen** [comment]
This has languished for a while and @marcelamelara has done a lot of other work improving docs, so we think we can close this.  If anyone has other doc cleanup they'd like to see please file new issues on the specific things you'd like to see?

There might be more work to do on the monotonic principle and something DevRel related to improve adoption of the problem but those seem like larger issues?  FYI @jkjell?
