### ISSUE TITLE
Ignoring unrecognised fields?

### ISSUE THREAD

**Issue by joshuagl** [in-toto/attestation#138]
SLSA's summary of the in-toto attestations parsing tools is being update to suggest that unrecognised fields are ignored "unless otherwise noted" https://github.com/slsa-framework/slsa/pull/628

Should we update the [parsing rules](https://github.com/in-toto/attestation/tree/main/spec#parsing-rules) to match?

**Comment by trishankatdatadog** [comment]
Yes
