### ISSUE TITLE
Provenance: rename `reproducibility`

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/attestation#14]
The name `recipe.reproducibility` sounds like whether it's a reproducible build or not, rather than the set of builder-controlled values that affected the build.

Maybe `recipe.environment`?

**Comment by aysylu** [comment]
Perhaps `recipe.params`, as in, parameters of the builder itself? This may be confusing in the presence of `recipe.arguments` though. Another option is `recipe.setup`. `recipe.environment` also makes sense.

**Comment by MarkLodato** [comment]
Another thought: `recipe.userControlledInputs` and `recipe.builderControlledInputs`, which is perhaps more self-documenting than `arguments` and `reproducibility`/`environment`/`whatever`.

**Comment by MarkLodato** [comment]
@nenaddedic suggested that "user" is unclear. Maybe: `recipe.externalInputs` and `recipe.builderEnvironment`?

**Comment by MarkLodato** [comment]
More ideas: User vs System, Untrusted vs Trusted.

**Comment by MarkLodato** [comment]
I renamed it to `environment`, which I think is good enough for 0.1 (the most urgent issue).

I'll leave this issue open to discuss possibly better names for the next release, in case users find it confusing.

**Comment by MarkLodato** [comment]
Actually, I'll just close this issue. We can open a new one if people have problems.
