### ISSUE TITLE
Relax subject.name requirements for v1

### ISSUE THREAD

**Issue by TomHennen** [in-toto/attestation#142]
[`subject.name` currently says](https://github.com/in-toto/attestation/blob/main/spec/v1.0-draft/statement.md#:~:text=subject%5B*%5D.name%20string%2C%20required):

'If the name is not meaningful, use "_"'

and 

'MUST be non-empty and unique within subject.'

This means that for cases where the name isn't meaningful, but there are multiple subjects, producers must specify a name, even if they don't care what it is.

That's usually fine, however when there is a large number of subjects this leads to a case where the size of the statement can become _very_ large and filled with information that is "not meaningful".  E.g. we have a case with ~92K subjects.  If we populate name with the filename (which we don't really care about) the resulting statement is ~25MB.  If, however, we don't set the subject name _at all_ then the resulting statement is ~11MB, a significant savings in size and generation time.

Suggestion:
Make `subject.name` _optional_ but require "if set MUST be set for _all_ subjects and MUST be non-empty and unique within subject".

This may cause trouble for parsers who turn the repeated subject field into a map keyed by name.  We would encourage them to generate some unique value when the encounter empty/missing names.

Does this sound reasonable?

**Comment by joshuagl** [comment]
Do we consider `_` to be non-empty? As written, I think not. But as intended, perhaps (so that we indicate we have chosen to omit, rather than accidentally omitted, the name)? 

Is it easy to generate a file size number with a name of `_` for all ~92k entries?

**Comment by MarkLodato** [comment]
I'd be fine relaxing the restriction, just making it optional. I'd also be OK making uniqueness a SHOULD instead of a MUST. I think the reason behind it was to allow consumers to differentiate between artifacts. If they don't need to do so, then I can see an argument for not forcing them.

**Comment by TomHennen** [comment]
> Do we consider `_` to be non-empty? As written, I think not. But as intended, perhaps (so that we indicate we have chosen to omit, rather than accidentally omitted, the name)?

I'd consider _ to be non-empty.  With this change we could remove the 'If the name is not meaningful, use "_"' bit, which is probably simpler in many ways?

> 
> Is it easy to generate a file size number with a name of `_` for all ~92k entries?

It's about 12MB.

**Comment by TomHennen** [comment]
> I'd be fine relaxing the restriction, just making it optional. I'd also be OK making uniqueness a SHOULD instead of a MUST. I think the reason behind it was to allow consumers to differentiate between artifacts. If they don't need to do so, then I can see an argument for not forcing them.

This would mess up folks that parse using a map, but then, maybe they shouldn't be doing that if the name isn't meaningful.  I'd be fine with it.

**Comment by marcelamelara** [comment]
I'm generally fine with making the `name` optional. This also might make it easier to change the field type of the `subject` to use the `descriptor` (formerly `reference`) type later down the line.

**Comment by AdamZWu** [comment]
> @MarkLodato @AdamZWu interested in your thoughts here

I really like the proposal.

IIUC the `name` field is really reserved for display purposes and there is no other functional behavior specified and/or planned on this field.

If an attestation creator does not want to provide it, that means they do not have a scenario/use case, and they don't care. So rather than forcing them to meet the letter of the law by cram in something meaningless thousands of times, not having the field is much more efficient, for both generation and consumption.

**Comment by TomHennen** [comment]
Great.  Let me send a PR.

**Comment by MarkLodato** [comment]
> IIUC the `name` field is really reserved for display purposes and there is no other functional behavior specified and/or planned on this field.

It is not just display purposes. It is also intended to be a selector to allow policies to distinguish between different output artifacts. For example, if a build produces "foo" and "foo.debug", a policy might only allow "foo" but not "foo.debug". This is something a bit unclear with the current version.
