### ISSUE TITLE
Add git hashing methods to DigestSet

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/attestation#145]
Now that we have `dirHash1` (formerly `goModuleH1`), I think it's worth adding `gitCommit`, `gitTree`, `gitBlob`, and (for completeness) `gitTag`). Two reasons:

1. It makes it more clear what's happening. Right now we just use `sha1` for a git commit, but we've had feedback that this is a bit confusing. By saying `gitCommit` it's obvious.
2. To allow `gitTree` as another way of hashing a tree object, similar to `dirHash1`. (Neither is perfect: `dirHash1` doesn't support permission bits or symlinks, while `gitTree` is SHA-1 based at least for now.)

I'm happy to do this, but wanted to file the issue to track.

**Comment by marcelamelara** [comment]
@in-toto/attestation-maintainers Do we pull this in as part of v1?

**Comment by adityasaky** [comment]
> Right now we just use sha1 for a git commit

Curious, is this currently used anywhere to address tags / trees / blobs?

**Comment by TomHennen** [comment]
> @in-toto/attestation-maintainers Do we pull this in as part of v1?

I think so, since it will just be defining new digest types it shouldn't be risky.  I suspect it could even happen very soon _after_ 1.0.  From chatting with @MarkLodato he is hoping to have it done for SLSA v1.  I think we just have to review?

**Comment by TomHennen** [comment]
> > Right now we just use sha1 for a git commit
> 
> Curious, is this currently used anywhere to address tags / trees / blobs?

SLSA uses `sha1` [to reference git commits](https://slsa.dev/provenance/v1-rc1#:~:text=%22resolvedDependencies%22%3A%20%5B%7B%0A%20%20%20%20%22uri%22%3A%20%22git%2Bhttps%3A//github.com/octocat/hello%2Dworld%40refs/heads/main%22%2C%0A%20%20%20%20%22digest%22%3A%20%7B%22sha1%22%3A%20%227fd1a60b01f91b314f59955a4e4d4e80d8edf11d%22%7D%0A%7D%5D).

**Comment by joshuagl** [comment]
I support landing this for the 1.0

**Comment by MarkLodato** [comment]
If we're doing this, do we need to then support Mercurial and Fossil too? (I don't see any other popular ones listed in https://en.wikipedia.org/wiki/Comparison_of_version-control_software#Technical_information that are based on hashes.)

**Comment by MarkLodato** [comment]
I think this is a regression from that standpoint. Previously you would just use `sha1` or similar, now you would use `hgCommit` (?). It seems OK to wait, but would be nice if we could have it ahead of time.

**Comment by TomHennen** [comment]
I would certainly review any PRs that defined those things? :)

**Comment by MarkLodato** [comment]
Actually this should be reopened - need to update existing examples to use this instead of `sha1`.

**Comment by MarkLodato** [comment]
Actually there are no examples of `sha1` in the current repo, other than examples.md which is not yet updated for v1.0.
