### ISSUE TITLE
Extension fields and dots

### ISSUE THREAD

**Issue by danzehme** [in-toto/attestation#147]
I am trying to store an SLSA Provenance which defers to the in-toto specification for extension fields:

> Extension fields: Producers MAY add extension fields to any JSON object by using a property name that is a [TypeURI](https://github.com/in-toto/attestation/blob/main/spec/v1.0-draft/scalar_field_types.md#TypeURI). The use of URI is to protect against name collisions. Consumers MAY parse and use these extensions if desired. The presence or absence of the extension field MUST NOT influence the meaning of any other field, and the field MUST follow the monotonic princple.

This format results in field names that are not legal in MongoDB.   The period is used in queries to query subdocuments.   I suspect this will be a problem with other document based stores.  It seems from the RFC that the TypeURI is meant to be used as a way of creating unique values (like its use for _type), but not intended as a way of creating unique field names.

**Comment by TomHennen** [comment]
Thanks for bringing this to our attention!

@in-toto/attestation-maintainers should we try to resolve for the 1.0 release (seems like an important use case).

**Comment by marcelamelara** [comment]
Makes sense to me to resolve this for v1.
