### ISSUE TITLE
Provenance: add a policy section

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/attestation#15]
In the provenance spec, add a policy section documenting how the provenance is intended to be consumed. This should aid readability, just as the Processing Model helped with the Envelope/Statement spec.

**Comment by marcelamelara** [comment]
I'd be interested in exploring this further, especially in the context of adding support for CDI. I also saw https://github.com/slsa-framework/slsa/issues/46. What is the status of these issues?

**Comment by MarkLodato** [comment]
I don't know of anyone working on this at the moment. It's just waiting for someone to have the time to do it, relative to the other issues :-)

**Comment by MarkLodato** [comment]
Moved to slsa-framework/slsa/issues/353
