### ISSUE TITLE
Include SLSA provenance v1 predicate language bindings with pre-generated code?

### ISSUE THREAD

**Issue by marcelamelara** [in-toto/attestation#200]
Per [this discussion](https://github.com/in-toto/in-toto-golang/pull/221#discussion_r1172704744), it sounds like there's interest in including pre-generated Golang bindings for the SLSA provenance v1 predicate as part of our in-toto/attestation/ go package.

Since SLSA already defines a proto for the [provenance predicate](https://github.com/slsa-framework/slsa/blob/main/docs/provenance/schema/v1/provenance.proto), it would be preferable not to have to create/maintain a separate copy in this repo, but rather use this proto to pre-generate the Golang (and other) bindings.

Thoughts? @MarkLodato @TomHennen

**Comment by TomHennen** [comment]
Yeah, I think we should definitely figure out what to do there.  Ideally we could take the same approach with the VSA, which I think [is only defined here](https://github.com/in-toto/attestation/tree/main/protos/in_toto_attestation/predicates/vsa/v0) and should probably take the exact same approach as SLSA provenance?  (If nothing else it probably needs to be updated for v1).

@chtiangg might also have some thoughts or interest in this.
