### ISSUE TITLE
Publish attestation maintainers meeting notes

### ISSUE THREAD

**Issue by marcelamelara** [in-toto/attestation#216]
It would be helpful for the remaining in-toto community for us to publish our meeting notes. This way, folks get insights into our latest activities and discussions. Should be relatively straight-forward to copy since the notes are already in markdown, too.

**Comment by tannerjones4075** [comment]
@marcelamelara is this issue still relevant? If so, I would like to help out with this.

**Comment by marcelamelara** [comment]
@tannerjones4075 thanks so much, yes, this is still something we'd like to get done!

**Comment by tannerjones4075** [comment]
@marcelamelara where are the meeting notes located and has there been any discussion in to where they should be published?

**Comment by marcelamelara** [comment]
Here's a link to the meeting notes: https://hackmd.io/fRKbxm6MT3GEz-_oSQtmYA

I don't think we've had a discussion around this, though my suggestion would be to add a small section to the main README and include the link there. Thanks again!

**Comment by tannerjones4075** [comment]
Awesome, thanks for the insight and link. I'll create a PR :)

**Comment by marcelamelara** [comment]
Thanks again @tannerjones4075 !
