### ISSUE TITLE
Provide better guidance on `materials`

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/attestation#25]
Currently it's unclear on what "complete" means for `materials`. Does it include materials used by the builder itself, e.g. the GitHub Actions orchestrator, or just the "runner"? To minimize the list, do we recommend that builds execute within a container? Is a container a sufficient security boundary? How confident do you need to be that it's coimplete?

My thinking is that we're shooting for "everything inside the runner container," and it's OK if malicious builds break out of the container, but you're capturing the intent of a "good" build.

Does this mean `completeness.materials` be an enum instead of a boolean?

@TomHennen FYI who raised this question.

**Comment by TomHennen** [comment]
I had been thinking that this would just include things _fetched_ for the specific build, but wouldn't necessarily include things that are 'included' with the use of a given runner.

I understand the desire to include this data.  I think there are two competing priorities: all the data needed to reproduce vs the data needed to see if an artifact meets it's SLSA (or any other policy).

Under SLSA the builder (including the runners!) will go through security review and accreditation.  To users that care if a given artifact meets it's policy, they probably don't care what artifacts come along with the build runner (it's already been checked for security properties).  Instead they probably care much more about what the build included for _this specific artifact_.

If we include both 'fetched' and 'included' materials in the materials field without having any way to distinguish between the two policy evaluation will be more difficult.  Some 'included' materials could interfere with policy evaluation even if they're totally fine.

So, I think it's very important to include the 'fetched' materials for policy evaluation.  I can see how 'included' materials is helpful for reproducibility, but I don't think they should be listed in 'materials' if they cannot be distinguished from 'fetched' materials.

**Comment by MarkLodato** [comment]
Good point.

What about for GitHub Actions, where the user selects which [VM Image](https://github.com/actions/virtual-environments) they use? Would that be considered "fetched" or "included"?

Also, note that the use case is not just reproduction but also vulnerability analysis.

**Comment by TomHennen** [comment]
My thought is:

If the user selects the VM image from a defined list, then the VM selection should go in recipe.arguments (and may only need to indicate 'ubuntu-18.04' or whatever).

if the user brings along their own VM image to do the build then it should be considered 'fetched'.

Agree on the vuln analysis.  Might be hard to reason about the results, but better to include it than not I suppose.

**Comment by TomHennen** [comment]
Just taking a look at this after thinking about log4j.

I think your suggestion is good.  One reason we don't want to include everything in the build infrastructure in the provenance is that the _builder_ might use log4j to log properties of the build, but _not_ include log4j in the built artifact.  If log4j were to be listed in materials then it would appear that everything that builder created was vulnerable to log4j, when in fact it was only just the builder.

**Comment by MarkLodato** [comment]
Moved to slsa-framework/slsa/issues/350
