### ISSUE TITLE
CamelCased protos

### ISSUE THREAD

**Issue by sherzberg-1** [in-toto/attestation#250]
The protos in https://github.com/in-toto/attestation/tree/main/protos/in_toto_attestation/v1 are camelCased (e.g. `downloadLocation`, `mediaType`, `predicateType`) when they should be snake_cased (as they are in https://github.com/in-toto/attestation/blob/main/protos/in_toto_attestation/predicates/provenance/v1/provenance.proto).

See https://protobuf.dev/programming-guides/style/#message-field-names.

**Comment by joshuagl** [comment]
Thank you for filing this! We are mostly protobuf novices on the project. :-)

Our current field definitions are inconsistent across the project, but we should standardise on the conventions documented in the protobuf programming guide. In fact, we already [claim to be following the conventions there](https://github.com/in-toto/attestation/blob/461c6b92b7f79f4bca73e6c69b68bf6121052221/docs/protos.md#protobuf-programming-practices).
