### ISSUE TITLE
Should in-toto managed vetted predicates type URIs point to GitHub repo?

### ISSUE THREAD

**Issue by marcelamelara** [in-toto/attestation#313]
Many predicateType URIs are non-existing. The TypeURI spec reads "SHOULD resolve to a human-readable description, but MAY be unresolvable.", so it is allowed to not to be there. But the non-existence of a predicateType URI seems to be causing confusion for some implementers when deciding when to pick a predicateType for generated attestations.

A possible solution may be to use the GitHub repo location for vetted predicates that are managed by in-toto as the predicateType URI. This would require an ITE-9 change, but pointing to the GH repo still signals that a predicate spec is managed by in-toto _and_ is resolvable.

_Originally posted by @fred-jonkhart in https://github.com/in-toto/attestation/issues/256#issuecomment-1829597525_

CC @adityasaky

**Comment by fred-jonkhart** [comment]
@marcelamelara, 
I can compose a detailed email to present my use case and the struggle I have. Note that my use case is not related to external software delivery. However, I feel that the same mechanisms should apply to any software artifact being build. Are you interested?

Furthermore, to add to this discussion I was sort of surprised that a predicateType should not resolve into a machine readable definition as well. Would a JSON schema not be handy to perform a minimum predicate validation?

**Comment by TomHennen** [comment]
> Would a JSON schema not be handy to perform a minimum predicate validation?

It certainly would!  We've looked into setting up the infrastructure to define and test some sort of validation mechanism before but haven't had the time to get it to really work out.

@mlieberman85 was also working on another project that did this sort of validation (not using JSON schema), but it hasn't been integrated here.

I think it would be fair to say we'd be open to reviewing PRs?

**Comment by mlieberman85** [comment]
https://github.com/kusaridev/spector/blob/main/tests/fixtures/slsa_provenance_v1_schema.json Here is a json schema I made using the Spector tool. 

So our Spector tool helps in both doing validation if you have complicated logic as well as it can generate json schemas.

**Comment by adityasaky** [comment]
> A possible solution may be to use the GitHub repo location for vetted predicates that are managed by in-toto as the predicateType URI. This would require an ITE-9 change, but pointing to the GH repo still signals that a predicate spec is managed by in-toto and is resolvable.

I don't have a strong opinion about this. FWIW, is this as simple as adding entries here: https://github.com/in-toto/in-toto.io/blob/master/public/_redirects? If so, maybe we set that up as an action item for new predicate types.

**Comment by mlieberman85** [comment]
I know a bit out of scope for this issue but I do wish the predicates were self-describing like json-ld.

**Comment by marcelamelara** [comment]
> I don't have a strong opinion about this. FWIW, is this as simple as adding entries here: https://github.com/in-toto/in-toto.io/blob/master/public/_redirects? If so, maybe we set that up as an action item for new predicate types.

I didn't realize we're already doing this for other parts the spec. Making this an action item for new predicates make a ton of sense to me.
