### ISSUE TITLE
Update `https://in-toto.io/Statement/v1` to point to latest version

### ISSUE THREAD

**Issue by darkfeline** [in-toto/attestation#346]
Currently, `https://in-toto.io/Statement/v1` points to `https://github.com/in-toto/attestation/blob/v1.0/spec/v1.0/statement.md` which is a bit old (e.g., it still references `DigestSet` instead of `ResourceDescriptor`).

Should it be updated to `https://github.com/in-toto/attestation/blob/v1.0.2/spec/v1/resource_descriptor.md` (or `https://github.com/in-toto/attestation/blob/main/spec/v1/resource_descriptor.md`)?

**Comment by marcelamelara** [comment]
Thanks for reporting this! We'll update the redirect, though this needs to happen in a separate repo.
