### ISSUE TITLE
provenance schema link returns 404, need change it to the new one.

### ISSUE THREAD

**Issue by WangLiGrace** [in-toto/attestation#378]
provenance schema link returns 404.
https://github.com/in-toto/attestation/blob/main/protos/in_toto_attestation/predicates/provenance/v1/provenance.proto#L1
![image](https://github.com/user-attachments/assets/165be3fe-442e-4661-9472-d6d2b4411caa)

**Comment by WangLiGrace** [comment]
I want to fix it.

**Comment by marcelamelara** [comment]
Thanks for the issue @WangLiGrace . The link that you posted in your original message doesn't lead to a 404 error, and correctly points to the protobuf defined in this repo. But the image you included shows the [SLSA framework repo](https://github.com/slsa-framework/slsa/tree/main). Which one are you trying to reach? 

To clarify, the protobuf definitions aren't the same. The .proto in the SLSA repo is for information only, and should not be used for any implementation. The .proto in this repo is the one used in several SLSA implementations.

**Comment by WangLiGrace** [comment]
> Thanks for the issue @WangLiGrace . The link that you posted in your original message doesn't lead to a 404 error, and correctly points to the protobuf defined in this repo. But the image you included shows the [SLSA framework repo](https://github.com/slsa-framework/slsa/tree/main). Which one are you trying to reach?
> 
> To clarify, the protobuf definitions aren't the same. The .proto in the SLSA repo is for information only, and should not be used for any implementation. The .proto in this repo is the one used in several SLSA implementations.

Hi @marcelamelara, I mean this link returns 404 ( https://github.com/slsa-framework/slsa/blob/main/docs/provenance/schema/v1/provenance.proto )

**Comment by marcelamelara** [comment]
I see your issue now, thank you for clarifying. Please feel free to submit a PR to fix that URL.
