### ISSUE TITLE
Provenance: consider splitting `builder.id`

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/attestation#40]
"Builder" primarily refers to the (id)entity generating the provenance, not the "runner" that actually did the build. This feels like it could easily be broken into two pieces to make things more clear (esp. at the lower SLSA levels): 1) authority that attests to the result of the build / content of provenance 2) runner that executes the build steps.

_Originally posted by @msuozzo in https://github.com/in-toto/attestation/pull/39#discussion_r651247813_

**Comment by TomHennen** [comment]
Any thoughts on how we would use these split identities?

Right now we're using the builder.id in policy evaluation so the user can specify what builders they accept.  Do we think people would want to do the same thing with the runner?  Or would the runner just be a nice piece of metadata to have?

**Comment by MarkLodato** [comment]
This hasn't really come up since, so i'll mark as WontFix for now. If there is interest, please open an issue on the slsa repo.
