### ISSUE TITLE
Create a protobuf schema for Statement & Predicates

### ISSUE THREAD

**Issue by TomHennen** [in-toto/attestation#48]
It would be helpful to have a protobuf schema that, when using JSON serialization, produces valid in-toto Statements & other predicates.  (Similar to what was done with [the DSSE envelope](https://github.com/secure-systems-lab/dsse/blob/master/envelope.proto).)

**Comment by letmaik** [comment]
Wouldn't JSON Schema make more sense? This would allow to describe fields and also get some level of (mostly structural) validation no matter how the JSON came into existence.

**Comment by TomHennen** [comment]
Maybe that too (it could be authoritative)?  We just have some users that want to work with protobuf and are trying to define their own proto schema but getting some bits wrong.

**Comment by marcelamelara** [comment]
Resolved in #131 and #162
