### ISSUE TITLE
Add redirect from https://in-toto.io/Attestation/v0.1 to the spec

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [in-toto/attestation#49]
Linked from https://github.com/in-toto/attestation/blob/main/spec/predicates/provenance.md

**Comment by MarkLodato** [comment]
@SantiagoTorres is it possible to set up the in-toto.io website to redirect the type aliases to the canonical definitions?

**Comment by SantiagoTorres** [comment]
Hmm, I wonder if we could instead make a template to render markdown of the spec for each attestation...

**Comment by SantiagoTorres** [comment]
Let me dig into this tonight and propose a way fw...

**Comment by MarkLodato** [comment]
For reference, we defined https://slsa.dev/provenance to redirect to https://slsa.dev/provenance/v0.1, which is where we serve the docs via GitHub pages.

For the in-toto Attestation spec, you could either do the same or just redirect to GitHub.

**Comment by adityasaky** [comment]
Closing this as https://github.com/in-toto/in-toto.io/pull/12 added redirects to this repo. Tracking rendering on website directly at https://github.com/in-toto/in-toto.io/issues/16.
