### ISSUE TITLE
Should the predicateType's hash be included as a digest?

### ISSUE THREAD

**Issue by jul-sh** [in-toto/attestation#81]
Per https://github.com/in-toto/attestation/blob/main/spec/README.md, the `predicateType` value should be a [TypeURI](https://github.com/in-toto/attestation/blob/main/spec/field_types.md#TypeURI) that defines both the shape and meaning of the predicate. 

Unlike most other URIs used in in-toto, the hash of the `predicateType` does not seem to be recorded in the attestation. 

I would be curious why this is the case, as this seems like a security vulnerability. The host of the URI referenced in the `predicateType` may silently update the content it responds with. This then creates a situation in which the meaning of the predicate object in the attestation is now different, with potentially unwelcome consequences. A consumer of the attestation must therefore trust the host of the `predicateType` to serve the same content that the attestation author referenced. 

It seems adding a [DigestSet](https://github.com/in-toto/attestation/blob/main/spec/field_types.md#DigestSet) for its content would remedy this?

**Comment by MarkLodato** [comment]
That's a reasonable concern, but you'd need to figure out what to actually hash.

1. The TypeURI is just a unique identifier that need not resolve to anything. The recommendation is to point it to human-readable documentation, but this is not required. Thus, you'd need to clarify what needs to be hashed, and state whether the URI must resolve to the thing-to-be-hashed.
2. What is the input to the hash function? You need some well defined serialization that describes the schema. But there is no such standard format. One could use protobuf, or JSON schema, or something else entirely. For https://slsa.dev/provenance/v0.1, we just use HTML. That would need to be agreed upon. If you use a text-based format, you'll need to handle cases where you add a trivial newline and now the hash changes.
3. It is a feature for the schema to [change](https://github.com/in-toto/attestation/blob/main/spec/versioning.md) without updating the URL, to allow for backwards-compatible additions. If we required hash checks, then I don't think we could allow consumers to accept newer minor versions.

**Comment by jul-sh** [comment]
Thanks for your reply, @MarkLodato! All good points.

I agree that making cryptographic verification fully compatible with the currently very permissive spec for `predicateType` seems challenging. The case of SLSA pointing to an HTML document is a good example. Documenting the hash of a HTML response seems like it might even do more harm than good, considering that the meaning of said document is likely influenced by the content of (non-hashed) URLs contained within.

I'm personally somewhat skeptical if the value add of this permissive approach (flexibility, the ability to update a schema after attestations based on it have already been released) trumps harm done by requiring attestation consumers to effectively trust the controller of the domain `predicateType` points to. The latter seems too steep a price to pay.

Hence my impulse would to look update the specification wrt the `predicateType` to allow for cryptographic verification. I would have some ideas, but finding the right solution is likely to require some consideration & discussion. 

In lieu of that, taking a step away from the larger specification, to my specific use-case. It is generating provenance files for use with a CLI (https://github.com/project-oak/transparent-release) that . Our initial approach was to define our own SLSA `buildType`, which would be documented as a JSON schema. This format lends itself to hashing more than others, so in lieu of a solution built into the standard I considered adding a `DigestSet` for the schema in a TypeURI extension field (the TypeURI property name being our `predicateType`). I realize however that consumers of our attestations would still need to trust both the SLSA predicateType, which doesn't seem ideal.

**Comment by jul-sh** [comment]
For additional context why trusting needing to trust `predicateType` / `buildType` author may be a problem in more advanced situations: one of the areas relating to attestations we're looking into is authorization logic. In essence that means taking multiple attestations (including by different authors and of different types), and combining them. 

A simple example attestation logic: take an Attestation_A by Reviewer_1 (identified by their signature) that making some claims about a given codebase, and an Attestation_B by Builder_2 (identified by their signature) that details the provenance of this binary built from this codebase. Assuming one trusts both Reviewer_1 and Builder_2 the claims about the properties of the codebase are then transferable to the associated binary. 

This type of logic can get relatively complex in the future, which then means that it involves potentially a host of predicateTypes which could be compromised. :)

**Comment by MarkLodato** [comment]
Thanks for expanding, @jul-sh. I agree that it is a desirable property, but it probably comes down to the concrete proposal. Feel free to propose something that we can discuss. IMO just adding a `digest` field would be confusing and likely lead to mistakes, so the proposal would probably need to be prescriptive on how exactly to use such a field. For example, it could mandate using JSON Schema and talk about backwards compatibility.

As a simpler alternative, have you considered including a hash in your URI? Then the producer and consumer would manually verify the hash before they read the spec and write their code.

**Comment by jul-sh** [comment]
thanks for your reply and input @MarkLodato! I definitely agree that it's not as simple as adding on a `digest` field to the existing approach. My main goal by raising this was to get more context and opinions on the concern. I definitely feel like I have those now. 

I'll sync with my team to see if we're interested in making a concrete proposal. In lieu of that we can patch a hash onto our specific solution, either with a separate key, or even as you mentioned as part of the URL schema parsed by the client, or by linking to a file on a trusted CaS proxy. 

Would you prefer to keep this issue open to document the concern or shall I close it?

**Comment by MarkLodato** [comment]
Let's leave it open because it's a legitimate concern.

**Comment by tiziano88** [comment]
Could we just use a plain hash **as** the `predicateType` URI? e.g. it may be set to `sha256:f3e737f4d50fbf6bb6053e3b8c72d6bf7f1a7229aacf2e9b4c97e9dd27cb1dcf` (which I believe is a valid URI), and we assume it will be resolved to the actual content via some other mechanism (e.g. shameless plug for https://github.com/google/ent , but anything with that shape would do). I believe this does not require changing anything in the spec, it would be just a potential (stronger) way of referring to the content, and may be offered as a suggestion / best practice, similarly to how we do when talking about pinning docker images and git repos.

**Comment by jul-sh** [comment]
@tiziano88 That specific scheme of recording a hash wouldn't technically comply with the `predicateType`'s Type of https://github.com/in-toto/attestation/blob/main/spec/field_types.md#TypeURI. It defers to RFC-3986, under which a URI must use one of the following schemes: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

But the general approach is worth considering for a future proposal. :)

**Comment by tiziano88** [comment]
You are right, the only draft I could find is https://github.com/hash-uri/hash-uri , but it seems it never went anywhere.

**Comment by jul-sh** [comment]
@tiziano88 A few alternatives to do this do exist that would be worth considering for a possible proposal. Eg https://datatracker.ietf.org/doc/html/rfc6920 seems to do basically what you suggested. An IANA registered URI scheme (`ni://`), creatively named "Naming Things with Hashes". 😅

**Comment by MarkLodato** [comment]
Yes, I recommend experimenting with `ni://`. You beat me to it 😄

**Comment by TomHennen** [comment]
Given that this issue hasn't been updated in quite a while, we'll assume there's not too strong of a use case for this, we'll close this issue as obsolete.

Please reopen if you feel strongly about it.
