### ISSUE TITLE
Only require 1 approver

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/attestation#86]
We keep finding ourselves lacking two separate reviewers for PRs. IMO it's unnecessarily burdensome to have two reviews for every change. Any objections to decreasing this down to 1?

**Comment by MarkLodato** [comment]
Great, thanks! I see it's changed now.

**Comment by joshuagl** [comment]
(FWIW I'd be happy to be a reviewer on changes where two reviewers is desirable).
